# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

jobs:
- job: Conviso_Appsec_Sast
  pool:
    vmImage: 'ubuntu-latest'
  container:
    image: 'convisoappsec/flowcli'
  variables:
    FLOW_PROJECT_CODE: '3qysm4zRpnk7Rnu-'

  steps:
  - bash: |
        conviso sast run
    env:
        FLOW_API_KEY: $(FLOW_API_KEY)
  - bash: | 
         conviso sca run
    env:
         FLOW_API_KEY: $(FLOW_API_KEY)  
